name: 打包推送

on:
  workflow_dispatch:
    inputs:
      PackageName:
        description: '需要打包的库名称，比如：zlib。等同于Packages内部的文件夹名称。'
        required: true
      PackageVersions:
        description: '需要打包库版本，比如：1.2.13。如果需要打包多个版本请使用空格分割。'
        required: true
jobs:
  Build:
    runs-on: windows-latest
    env:
        PackageName: ${{ inputs.PackageName }}
        PackageVersions: ${{ inputs.PackageVersions }}
    steps:
    - uses: actions/checkout@v2

    - name: 打包
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          $PackageVersions = "${{env.PackageVersions}}"
          foreach ($PackageVersion in $PackageVersions.Split(' ')) 
          {
              pushd ".\Packages\${{env.PackageName}}\$PackageVersion"
              &.\Pack.ps1
              popd
          }

    - uses: actions/upload-artifact@v2
      with:
        path: |
            Packages\${{env.PackageName}}\*\*.nupkg

    - name: 内容发布
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
         # 把生成的nuget包发布到nuget中     
         foreach ($Item in Get-ChildItem -Path .\Packages\${{env.PackageName}}\*\*.nupkg) 
         {
             &nuget push $Item -ApiKey ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json
             if($lastexitcode -ne 0)
             {
                 throw "nuget push $Item失败！退出代码：$lastexitcode"
             }
         }
